[package]
name = "jam_list_hashing_service"
version = "0.1.0"
authors = ["ericoseid"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rust-crypto = "0.2.36"
json = "0.12.4"